const data = {
  products: [
    {
      id: 1,
      name: "Nike Slim Shirt",
      slug: "nike-slim",
      category: "Shirts",
      image: "images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "hight quality shirt",
    },
    {
        id: 2,
        name: "Nike Slim Shirt",
        slug: "nike-slim",
        category: "Shirts",
        image: "images/p1.jpg",
        price: 120,
        countInStock: 10,
        brand: "Nike",
        rating: 4.5,
        numReviews: 10,
        description: "hight quality shirt",
      },
      {
        id: 3,
        name: "Nike Slim Shirt",
        slug: "nike-slim",
        category: "Shirts",
        image: "images/p1.jpg",
        price: 120,
        countInStock: 10,
        brand: "Nike",
        rating: 4.5,
        numReviews: 10,
        description: "hight quality shirt",
      },
      {
        id: 4,
        name: "Nike Slim Shirt",
        slug: "nike-slim",
        category: "Shirts",
        image: "images/p1.jpg",
        price: 120,
        countInStock: 10,
        brand: "Nike",
        rating: 4.5,
        numReviews: 10,
        description: "hight quality shirt",
      },
      {
        id: 5,
        name: "Nike Slim Shirt",
        slug: "nike-slim",
        category: "Shirts",
        image: "images/p1.jpg",
        price: 120,
        countInStock: 10,
        brand: "Nike",
        rating: 4.5,
        numReviews: 10,
        description: "hight quality shirt",
      },
  ],
};

export default data;